export const accountNav = [
	[
		{ label: "Account", icon: "fa-light fa-user", href: "/account" },
		{ label: "Profile", icon: "fa-light fa-id-badge", href: "/account/profile" },
		{ label: "Settings", icon: "fa-light fa-cog", href: "/account/settings" },
	],
	[{ label: "Home", icon: "fa-light fa-house", href: "/" }],
]


export const navigationData = [
	{
		slug: "app",
		label: "App", 
		href: null,
		target: "_self", 
		icon: "fa-light fa-grid-2", 
		permissions: [],
		classes: "",
		align: null,
		children: [
			{
				slug: "overview",
				label: "Overview", 
				href: "/app/overview",
				target: "_self", 
				icon: "fa-light fa-gauge", 
				permissions: [],
				classes: "",
				align: null,
			},
			{
				slug: "news",
				label: "News", 
				href: "/app/news",
				target: "_self", 
				icon: "fa-light fa-newspaper", 
				permissions: [],
				classes: "",
				align: null,
			},
			{
				slug: "explore",
				label: "Explore", 
				href: "/app/explore",
				target: "_self", 
				icon: "fa-light fa-compass", 
				permissions: [],
				classes: "",
				align: null,
			},
			{
				slug: "research",
				label: "Research", 
				href: "/app/research",
				target: "_self", 
				icon: "fa-light fa-flask", 
				permissions: [],
				classes: "",
				align: null,
			},
			{
				slug: "add",
				label: "Add", 
				href: "/app/add",
				target: "_self", 
				icon: "fa-light fa-plus", 
				permissions: [],
				classes: "",
				align: null,
			},
		],
	},

	{
		slug: "account",
		label: "Account", 
		href: null,
		target: "_self", 
		icon: "fa-light fa-user", 
		permissions: [],
		classes: "",
		align: null,
		children: [
			{
				slug: "profile",
				label: "Your profile", 
				href: "/account/profile",
				target: "_self", 
				icon: "fa-light fa-id-badge", 
				permissions: [],
				classes: "",
				align: null,
			},
			{
				slug: "security",
				label: "Security", 
				href: "/account/security",
				target: "_self", 
				icon: "fa-light fa-shield", 
				permissions: [],
				classes: "",
				align: null,
			},
			{
				slug: "settings",
				label: "Settings", 
				href: "/account/settings",
				target: "_self", 
				icon: "fa-light fa-cog", 
				permissions: [],
				classes: "",
				align: null,
				children: [
					{
						slug: "Avatar",
						label: "Avatar", 
						href: "/account/settings/avatar",
						target: "_self", 
						icon: "fa-light fa-image", 
						permissions: [],
						classes: "",
						align: null,
					},
					{
						slug: "Details",
						label: "Details", 
						href: "/account/settings/details",
						target: "_self", 
						icon: "fa-light fa-file-signature", 
						permissions: [],
						classes: "",
						align: null,
					},
					{
						slug: "billing",
						label: "Billing", 
						href: "/account/settings/billing",
						target: "_self", 
						icon: "fa-light fa-credit-card", 
						permissions: [],
						classes: "",
						align: null,
					},
					{
						slug: "password",
						label: "Password", 
						href: "/account/settings/password",
						target: "_self", 
						icon: "fa-light fa-lock", 
						permissions: [],
						classes: "",
						align: null,
					},
				]
			},
		],
	},

		{
		slug: "billing",
		label: "Billing", 
		href: null,
		target: "_self", 
		icon: "fa-light fa-credit-card", 
		permissions: [],
		classes: "",
		align: null,
		children: [
			{
				slug: "orders",
				label: "Orders", 
				href: "/account/orders",
				target: "_self", 
				icon: "fa-light fa-shopping-cart", 
				permissions: [],
				classes: "",
				align: null,
			},
			{
				slug: "invoices",
				label: "Invoices", 
				href: "/account/invoices",
				target: "_self", 
				icon: "fa-light fa-file-invoice", 
				permissions: [],
				classes: "",
				align: null,
			},
			{
				slug: "subscriptions",
				label: "Subscriptions", 
				href: "/account/subscriptions",
				target: "_self", 
				icon: "fa-light fa-repeat", 
				permissions: [],
				classes: "",
				align: null,
			},
		],
	},


	{
		slug: "admin",
		label: "Admin", 
		href: null,
		target: "_self", 
		icon: "fa-light fa-shield-halved", 
		permissions: ["administrator"],
		classes: "",
		align: null,
		children: [
			{
				slug: "admin-panel",
				label: "Dashboard", 
				href: "/admin/panel",
				target: "_self", 
				icon: "fa-light fa-toolbox", 
				permissions: [],
				classes: "",
				align: null,
			},
			{
				slug: "admin-users",
				label: "Users", 
				href: "/admin/users",
				target: "_self", 
				icon: "fa-light fa-users-crown", 
				permissions: [],
				classes: "",
				align: null,
			},
			{
				slug: "admin-orders",
				label: "Orders", 
				href: "/admin/orders",
				target: "_self", 
				icon: "fa-light fa-shopping-cart", 
				permissions: [],
				classes: "",
				align: null,
			},
			{
				slug: "admin-configuration",
				label: "Configuration", 
				href: "/admin/configuration",
				target: "_self", 
				icon: "fa-light fa-cog", 
				permissions: [],
				classes: "",
				align: null,
			},
			{
				slug: "admin-health",
				label: "Health", 
				href: "/admin/health",
				target: "_self", 
				icon: "fa-light fa-heart-pulse", 
				permissions: [],
				classes: "",
				align: null,
			},
			{
				slug: "admin-dev",
				label: "Dev tools", 
				href: "/admin/dev",
				target: "_self", 
				icon: "fa-light fa-code", 
				permissions: [],
				classes: "",
				align: null,
			},
		],
	},

]