@baseUrl = http://localhost:4000/api/v1

### Vendor info (GET)
GET {{baseUrl}}/auth/vendor/discord

### Vendor login (POST)
# @name vendorTokens
POST {{baseUrl}}/auth/vendor/discord
Content-Type: application/json

{
  "code": "sandbox-code",
  "token": "sandbox-code",
  "email": "demo+discord@example.com"
}

### Me using vendor access token
@accessToken = {{vendorTokens.response.body.$.data.tokens.access.token}}
GET {{baseUrl}}/auth/me
Authorization: Bearer {{accessToken}}
