@baseUrl = http://localhost:4000/api/v1

### Vendor info (GET)
POST {{baseUrl}}/account/auth/vendor/discord
Content-Type: application/json

{}

### Vendor login (POST)
# @name vendorTokens
POST {{baseUrl}}/account/auth/vendor/discord/login
Content-Type: application/json

{
  "code": "sandbox-code",
  "token": "sandbox-code",
  "email": "demo+discord@example.com"
}

### Me using vendor access token
@accessToken = {{vendorTokens.response.body.$.data.tokens.access.token}}
POST {{baseUrl}}/account/me
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{}
